# 测试环境
MYSQL_HOST = 'localhost'
MYSQL_DBNAME = 'test'
MYSQL_USER = 'root'
MYSQL_PASSWORD = '12345678'
MYSQL_PORT = 3306


# 生产环境
# MYSQL_HOST = ''
# MYSQL_DBNAME = ''
# MYSQL_USER = ''
# MYSQL_PASSWORD = ''
# MYSQL_PORT =
